### ISSUE TITLE
Windows supported?

### ISSUE THREAD

**Issue by simonmichael** [juhp/stack-clean-old#5]
Someone tried to install stack-clean-old on MS Windows in IRC today, and failed because it depends on `unix`, via `extra` probably.

**Comment by juhp** [comment]
Thanks for reporting - I will look into it later then, though i don't have Windows myself.

**Comment by juhp** [comment]
I guess it is filemanip, which depends on unix-compat...
Maybe it can be worked around easily.

**Comment by simonmichael** [comment]
Isn't it extra, which depends on unix ? unix-compat works on windows.

**Comment by juhp** [comment]
That's depends how you are looking :)

extra is developed by Neil Mitchell, who I believe is a Windows user...
https://github.com/ndmitchell/extra/blob/master/extra.cabal#L40
https://hackage.haskell.org/package/extra-1.7.9/extra.cabal

Actually looking closer at unix-compat, it does indeed also seem to build without unix (with Win32 instead) on Windows:
https://hackage.haskell.org/package/unix-compat-0.5.3/unix-compat.cabal

Then I am not sure what the actually issue is here...
It would be helpful to see the error message.

(If it really is a extra issue, then that should be reported there.)

It is also possible I make some Unix assumptions in stack-clean-old...

**Comment by juhp** [comment]
I am going to go ahead and close this for now.

If more information becomes available please comment or open a new ticket, thanks
