### ISSUE TITLE
stack-clean-old: More than one OS systems found

### ISSUE THREAD

**Issue by pierre-thierry** [juhp/stack-clean-old#7]
My `~/.stack/programs/` and `~/.stack/snapshots/` contain:
- x86_64-linux-nix/
- x86_64-linux-tinfo6/

Running `stack-clean-old` gives me the following error:
```shell
~:$ stack-clean-old list
stack-clean-old: More than one OS systems found
```

**Comment by juhp** [comment]
Thanks for the report.

Any suggestions/ideas for how to handle multiple systems like this?

**Comment by juhp** [comment]
I have added an `--os-system` (`-o`) option (hmm maybe --os would also be sufficient or --platform).
Please try [0.4.2](https://hackage.haskell.org/package/stack-clean-old-0.4.2) and see if it works for you.
